../../rtl/TargetNoC.v
../../rtl/crossbar.v
../../rtl/input_controller.v
../../rtl/input_stage.v
../../rtl/mtx_arbiter.v
../../rtl/mux_data_valid_6to1.v
../../rtl/mux_ready_6to1.v
../../rtl/output_stage.v
../../rtl/route_calculator.v
../../rtl/router.v
../../rtl/SyncFIFO_RTL.v
../../rtl/vc_allocator.v
./srcs/top_tb.sv